# Generated by Django 2.1.1 on 2018-09-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='用户手机号')),
                ('nickname', models.CharField(max_length=40, unique=True, verbose_name='用户昵称')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='用户性别')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='用户得分')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='users.MyUser', verbose_name='外键用户id')),
            ],
        ),
        migrations.CreateModel(
            name='TokenLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, verbose_name='api用Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tokenlogin', to='users.MyUser', verbose_name='外键用户id')),
            ],
        ),
    ]
