# Generated by Django 2.1.1 on 2018-09-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='expires',
            field=models.DateTimeField(auto_now=True, verbose_name='短信验证码创建时间'),
        ),
    ]
