# Generated by Django 2.1.1 on 2018-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180918_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='user',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='phone',
            field=models.CharField(default=111, max_length=20, unique=True, verbose_name='用户手机号'),
            preserve_default=False,
        ),
    ]
